pipeline {
    agent any
    environment { 
        IMAGE_NAME_DOC = "mukeshphulwani66/pipelinedemo:${BUILD_NUMBER}"
    }
    stages {
        stage('GitHub Clone Preparation') {
            steps {
                echo 'Cloning Repository'
                withCredentials([gitUsernamePassword(credentialsId: 'github-token')]) {
                    git  url: 'https://github.com/aslamabid/react-docker-nginx.git', branch: 'master'
                }
            }
        }

        stage('build') {
            steps {
                echo 'building image'
                sh 'docker compose -f docker-compose.prod.yml build'
            }
        }
    }
}
